export {
  DEFAULT_TERMINAL_COLS,
  DEFAULT_TERMINAL_ROWS,
  TERMINAL_TERM_TYPE,
  MIN_TERMINAL_COLS,
  MAX_TERMINAL_COLS,
  MIN_TERMINAL_ROWS,
  MAX_TERMINAL_ROWS,
  SSH_TERMINAL_CONNECTION_ID_PREFIX,
  SSH_TERMINAL_WINDOW_PIXELS,
  TERMINAL_OUTPUT_ENCODING,
} from "@shared/common";
