import { useEffect, useState } from "react";
import type { Control, FieldValues } from "react-hook-form";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { TooltipHint } from "@/components/ui/tooltip";
import {
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form";
import type { TemplateVariable } from "../types";
import { groupTemplateVariables, isSensitiveVariable } from "../utils/field-utils";
import {
  generateMagicEnvValue,
  isAutoGeneratedMagicVariable,
  parseMagicEnvCommand,
} from "../utils/service-magic-env";

const MASKED_VALUE = "************";

type DynamicDeployFieldsProps<TFieldValues extends FieldValues> = {
  control: Control<TFieldValues>;
  variables: TemplateVariable[];
  isEditing: boolean;
};

function EyeIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx="12" cy="12" r="3" stroke="currentColor" strokeWidth="2" />
    </svg>
  );
}

function EyeOffIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M9.9 4.24A10.94 10.94 0 0 1 12 4c6.5 0 10 7 10 7a18.5 18.5 0 0 1-2.16 3.19M6.12 6.12A18.5 18.5 0 0 0 2 12s3.5 7 10 7a10.94 10.94 0 0 0 2.76-.36M6.12 6.12 2 2m4.12 4.12 15.76 15.76"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function RegenerateIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M3 3v5h5M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M16 21h5v-5"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function formatRevealedValue(variable: TemplateVariable, value: unknown): string {
  if (value === undefined || value === null || value === "") {
    return "—";
  }

  if (variable.type === "boolean") {
    return value ? "true" : "false";
  }

  return String(value);
}

function canRegenerateValue(variableName: string): boolean {
  return (
    isAutoGeneratedMagicVariable(variableName) ||
    isSensitiveVariable(variableName)
  );
}

function regenerateValue(variableName: string): string {
  const command = parseMagicEnvCommand(variableName);
  if (command) {
    return generateMagicEnvValue(command);
  }
  return generateMagicEnvValue("PASSWORD");
}

function TextVariableInput({
  variable,
  value,
  onChange,
  "aria-invalid": ariaInvalid,
}: {
  variable: TemplateVariable;
  value: unknown;
  onChange: (value: string | number | undefined) => void;
  "aria-invalid"?: boolean;
}) {
  return (
    <Input
      type={variable.type === "number" ? "number" : "text"}
      value={value === undefined || value === null ? "" : String(value)}
      autoComplete="off"
      aria-invalid={ariaInvalid}
      className={ariaInvalid ? "deploy-var-input--error" : undefined}
      onChange={(event) => {
        if (variable.type === "number") {
          const raw = event.target.value;
          if (raw === "") {
            // Use empty string — react-hook-form treats `undefined` as "revert to default".
            onChange("");
            return;
          }
          const parsed = Number(raw);
          onChange(Number.isNaN(parsed) ? "" : parsed);
          return;
        }
        onChange(event.target.value);
      }}
    />
  );
}

function VariableRow<TFieldValues extends FieldValues>({
  control,
  variable,
  isEditing,
  isRequired,
}: {
  control: Control<TFieldValues>;
  variable: TemplateVariable;
  isEditing: boolean;
  isRequired: boolean;
}) {
  const [revealed, setRevealed] = useState(false);
  const showRegenerate = isEditing && canRegenerateValue(variable.name);

  useEffect(() => {
    setRevealed(false);
  }, [isEditing]);

  return (
    <FormField
      control={control}
      name={variable.name as never}
      render={({ field, fieldState }) => (
        <FormItem
          className={`deploy-var-row${fieldState.error ? " deploy-var-row--error" : ""}`}
        >
          <span className="deploy-var-name">
            {variable.name}
            {isRequired ? (
              <span className="form-field-required" aria-hidden="true">
                {" "}
                *
              </span>
            ) : null}
          </span>

          <div className="deploy-var-value-cell">
            {isEditing ? (
              <FormControl>
                {variable.type === "boolean" ? (
                  <div className="deploy-var-boolean-edit">
                    <span className="deploy-var-boolean-label">
                      {field.value ? "Enabled" : "Disabled"}
                    </span>
                    <Switch
                      checked={Boolean(field.value)}
                      onCheckedChange={field.onChange}
                    />
                  </div>
                ) : (
                  <TextVariableInput
                    variable={variable}
                    value={field.value}
                    onChange={field.onChange}
                    aria-invalid={fieldState.error ? true : undefined}
                  />
                )}
              </FormControl>
            ) : (
              <span className="deploy-var-value">
                {revealed
                  ? formatRevealedValue(variable, field.value)
                  : MASKED_VALUE}
              </span>
            )}

            {!isEditing ? (
              <button
                type="button"
                className="deploy-var-action-btn"
                onClick={() => setRevealed((value) => !value)}
                aria-label={revealed ? "Hide value" : "Show value"}
                aria-pressed={revealed}
              >
                {revealed ? <EyeOffIcon /> : <EyeIcon />}
              </button>
            ) : showRegenerate ? (
              <TooltipHint content="Regenerate value">
                <button
                  type="button"
                  className="deploy-var-action-btn"
                  onClick={() => field.onChange(regenerateValue(variable.name))}
                  aria-label={`Regenerate ${variable.name}`}
                >
                  <RegenerateIcon />
                </button>
              </TooltipHint>
            ) : (
              <span className="deploy-var-action-spacer" aria-hidden />
            )}
          </div>

          <FormMessage className="form-field-error deploy-var-error" role="alert" />
        </FormItem>
      )}
    />
  );
}

function VariableList<TFieldValues extends FieldValues>({
  control,
  variables,
  isEditing,
  isRequired,
}: {
  control: Control<TFieldValues>;
  variables: TemplateVariable[];
  isEditing: boolean;
  isRequired: boolean;
}) {
  if (variables.length === 0) return null;

  return (
    <div className="deploy-var-list">
      {variables.map((variable) => (
        <VariableRow
          key={variable.name}
          control={control}
          variable={variable}
          isEditing={isEditing}
          isRequired={isRequired}
        />
      ))}
    </div>
  );
}

export function DynamicDeployFields<TFieldValues extends FieldValues>({
  control,
  variables,
  isEditing,
}: DynamicDeployFieldsProps<TFieldValues>) {
  const [advancedOpen, setAdvancedOpen] = useState(false);

  if (variables.length === 0) {
    return (
      <p className="deploy-form-empty-state">
        No configuration required for this template. Platform defaults will be
        applied automatically when you deploy.
      </p>
    );
  }

  const { ports, required, optional } = groupTemplateVariables(variables);
  const requiredVariables = [...ports, ...required];

  return (
    <div className="deploy-vars-panel">
      <section className="deploy-vars-section">
        <header className="deploy-vars-section-header">
          <h2>Required variables</h2>
          <p>Configuration values needed before deployment can proceed.</p>
        </header>
        <VariableList
          control={control}
          variables={requiredVariables}
          isEditing={isEditing}
          isRequired
        />
      </section>

      {optional.length > 0 && (
        <section className="deploy-vars-section deploy-vars-advanced-section">
          <button
            type="button"
            className="deploy-vars-advanced-toggle"
            onClick={() => setAdvancedOpen((open) => !open)}
            aria-expanded={advancedOpen}
          >
            <span>Advanced Options</span>
            <svg
              className={`deploy-vars-advanced-chevron${advancedOpen ? " is-open" : ""}`}
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              aria-hidden
            >
              <path
                d="M6 9l6 6 6-6"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </button>

          {advancedOpen ? (
            <VariableList
              control={control}
              variables={optional}
              isEditing={isEditing}
              isRequired={false}
            />
          ) : null}
        </section>
      )}
    </div>
  );
}
