import { z } from "zod";
import type { ApiTemplate, TemplateVariable } from "../types";
import { isFormRequiredVariable, isPortVariable } from "./field-utils";
import {
  generateMagicEnvValue,
  isAutoGeneratedMagicVariable,
  parseMagicEnvCommand,
} from "./service-magic-env";

const TEMPLATE_ACCENT_COLORS: Record<string, string> = {
  postgresql: "#336791",
  postgres: "#336791",
  mongodb: "#47A248",
  mongo: "#47A248",
  redis: "#DC382D",
  n8n: "#EA4B71",
  mysql: "#00758F",
  kafka: "#231F20",
  rabbitmq: "#FF6600",
  elasticsearch: "#005571",
  minio: "#C72C48",
  grafana: "#F46800",
  prometheus: "#E6522C",
  nginx: "#009639",
  wordpress: "#21759B",
  nextcloud: "#0082C9",
  gitea: "#609926",
  keycloak: "#4D7A97",
  traefik: "#24A1C1",
  portainer: "#13BEF9",
};

export function getTemplateAccentColor(slug: string): string {
  const lower = slug.toLowerCase();
  for (const [key, color] of Object.entries(TEMPLATE_ACCENT_COLORS)) {
    if (lower === key || lower.startsWith(key)) {
      return color;
    }
  }

  let hash = 0;
  for (let i = 0; i < slug.length; i++) {
    hash = (hash * 31 + slug.charCodeAt(i)) & 0xffffff;
  }
  return `#${hash.toString(16).padStart(6, "0")}`;
}

function parseNumberFormValue(val: unknown): number | undefined {
  if (val === "" || val === null || val === undefined) {
    return undefined;
  }

  if (typeof val === "number") {
    return Number.isNaN(val) ? undefined : val;
  }

  const parsed = Number(val);
  return Number.isNaN(parsed) ? undefined : parsed;
}

const numberFormInput = z.union([
  z.number(),
  z.string(),
  z.literal(""),
  z.null(),
  z.undefined(),
]);

function numberFieldSchema(isRequired: boolean): z.ZodTypeAny {
  if (isRequired) {
    return numberFormInput
      .refine((val) => parseNumberFormValue(val) !== undefined, {
        message: "This field is required",
      })
      .transform((val) => parseNumberFormValue(val) as number);
  }

  return numberFormInput.transform((val) => parseNumberFormValue(val));
}

function variableFieldSchema(variable: TemplateVariable): z.ZodTypeAny {
  const isRequired = isFormRequiredVariable(variable);

  if (variable.type === "boolean") {
    return isRequired ? z.boolean() : z.boolean().optional();
  }

  if (variable.type === "number") {
    return numberFieldSchema(isRequired);
  }

  return isRequired
    ? z.string().trim().min(1, "This field is required")
    : z.string().trim().optional();
}

export function buildDeployFormSchema(template: ApiTemplate) {
  const variables = template.variables ?? [];
  const shape: Record<string, z.ZodTypeAny> = {};

  for (const variable of variables) {
    shape[variable.name] = variableFieldSchema(variable);
  }

  return z.object(shape);
}

export type DeployFormValues = z.infer<
  ReturnType<typeof buildDeployFormSchema>
>;

export function buildDeployFormDefaults(
  template: ApiTemplate,
): Record<string, string | number | boolean | undefined> {
  const defaults: Record<string, string | number | boolean | undefined> = {};

  for (const variable of template.variables ?? []) {
    if (variable.defaultValue !== null && variable.defaultValue !== "") {
      defaults[variable.name] = variable.defaultValue;
      continue;
    }

    if (variable.type === "boolean") {
      defaults[variable.name] = false;
      continue;
    }

    if (isAutoGeneratedMagicVariable(variable.name)) {
      const command = parseMagicEnvCommand(variable.name);
      if (command) {
        defaults[variable.name] = generateMagicEnvValue(command);
      }
    }
  }

  return defaults;
}

export function splitDeployFormValues(
  variables: TemplateVariable[],
  values: Record<string, unknown>,
): { env: Record<string, string>; ports: Record<string, string> } {
  const env: Record<string, string> = {};
  const ports: Record<string, string> = {};

  for (const variable of variables) {
    const raw = values[variable.name];
    if (raw === undefined || raw === null || raw === "") {
      continue;
    }

    const serialized = String(raw);
    if (isPortVariable(variable.name)) {
      ports[variable.name] = serialized;
    } else {
      env[variable.name] = serialized;
    }
  }

  return { env, ports };
}
