/**
 * Coolify-style SERVICE_* magic variable generation (mirrors compose-parser).
 * @see apps/control-panel-app/templates/README.md
 */

const MAGIC_PREFIX = "SERVICE_";
const PORT_KEY_PREFIX = "SERVICE_PORT_";

function randomBytes(length: number): Uint8Array {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
}

function randomAlphanumeric(length: number): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  const bytes = randomBytes(length);

  return Array.from(bytes, (byte) => chars[byte % chars.length]).join("");
}

function randomHex(byteLength: number): string {
  return Array.from(randomBytes(byteLength), (byte) =>
    byte.toString(16).padStart(2, "0"),
  ).join("");
}

function randomPassword(length: number, withSymbols: boolean): string {
  let chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  if (withSymbols) {
    chars += "!@#$%^&*";
  }

  const bytes = randomBytes(length);

  return Array.from(bytes, (byte) => chars[byte % chars.length]).join("");
}

/** Parse SERVICE_{COMMAND}_{IDENTIFIER} into a generation command. */
export function parseMagicEnvCommand(key: string): string | null {
  if (!key.startsWith(MAGIC_PREFIX)) {
    return null;
  }

  const underscoreCount = (key.match(/_/g) ?? []).length;

  if (underscoreCount === 2) {
    if (
      key.startsWith("SERVICE_FQDN") ||
      key.startsWith("SERVICE_URL") ||
      key.startsWith(PORT_KEY_PREFIX)
    ) {
      if (key.startsWith(PORT_KEY_PREFIX)) {
        return "PORT";
      }

      return key.slice(MAGIC_PREFIX.length, key.lastIndexOf("_"));
    }

    return key.slice(MAGIC_PREFIX.length, key.lastIndexOf("_"));
  }

  if (underscoreCount === 3) {
    if (key.startsWith("SERVICE_FQDN") || key.startsWith("SERVICE_URL")) {
      return key.slice(
        MAGIC_PREFIX.length,
        key.indexOf("_", MAGIC_PREFIX.length),
      );
    }

    return key.slice(MAGIC_PREFIX.length, key.lastIndexOf("_"));
  }

  return null;
}

export function generateMagicEnvValue(command: string): string {
  switch (command) {
    case "PASSWORD":
      return randomAlphanumeric(24);
    case "PASSWORD_64":
      return randomAlphanumeric(64);
    case "PASSWORDWITHSYMBOLS":
      return randomPassword(24, true);
    case "PASSWORDWITHSYMBOLS_64":
      return randomPassword(64, true);
    case "BASE64":
    case "BASE64_32":
      return randomAlphanumeric(32);
    case "BASE64_64":
      return randomAlphanumeric(64);
    case "BASE64_128":
      return randomAlphanumeric(128);
    case "USER":
      return randomAlphanumeric(16);
    case "LOWERCASEUSER":
      return randomAlphanumeric(16).toLowerCase();
    case "HEX_32":
      return randomHex(16);
    case "HEX_64":
      return randomHex(32);
    case "HEX_128":
      return randomHex(64);
    default:
      return randomAlphanumeric(32);
  }
}

export function isAutoGeneratedMagicVariable(name: string): boolean {
  const command = parseMagicEnvCommand(name);
  return (
    command !== null &&
    command !== "PORT" &&
    command !== "FQDN" &&
    command !== "URL"
  );
}
