export enum ServerErrorCode {
  CREDENTIALS_NOT_FOUND = "CREDENTIALS_NOT_FOUND",
  SSH_PAYLOAD_REQUIRED = "SSH_PAYLOAD_REQUIRED",
  AUTH_FAILED = "AUTH_FAILED",
  CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT",
  HOST_UNREACHABLE = "HOST_UNREACHABLE",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  ALREADY_CONNECTED = "ALREADY_CONNECTED",
  CONNECTION_FAILED = "CONNECTION_FAILED",
  DELETE_FAILED = "DELETE_FAILED",
  HOST_ALREADY_EXISTS = "HOST_ALREADY_EXISTS",
}
