export const SSH_DEFAULTS = {
  KEEPALIVE_INTERVAL: 10000, // ms
  KEEPALIVE_COUNT_MAX: 3,
  READY_TIMEOUT: 20000, // ms
  COMMAND_TIMEOUT: 30000, // ms
};

export const AUTH_TYPE = {
  PRIVATE_KEY: "PRIVATE_KEY",
  PASSWORD: "PASSWORD",
};
